# Generated by Django 4.2.6 on 2023-10-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
